"""Add status table

Revision ID: 1d6c79218b3e
Revises: 886fe40dd4f1
Create Date: 2018-03-13 05:29:22.923849

"""

# revision identifiers, used by Alembic.
revision = '1d6c79218b3e'
down_revision = '886fe40dd4f1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
import sqlalchemy_jsonfield

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('last_output', sa.Text(), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.DateTime(), nullable=False),
    sa.Column('run_time', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_status_name'), 'plugin_status', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_status_name'), table_name='plugin_status')
    op.drop_table('plugin_status')
    # ### end Alembic commands ###
