"""Whoops, forgot a column

Revision ID: 2939691825b4
Revises: b9de14a99010
Create Date: 2018-02-21 20:49:53.373174

"""

# revision identifiers, used by Alembic.
revision = '2939691825b4'
down_revision = 'b9de14a99010'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
import sqlalchemy_jsonfield

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hentai_releases', sa.Column('series_name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_hentai_releases_series_name'), 'hentai_releases', ['series_name'], unique=False)
    op.add_column('manga_releases', sa.Column('series_name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_manga_releases_series_name'), 'manga_releases', ['series_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manga_releases_series_name'), table_name='manga_releases')
    op.drop_column('manga_releases', 'series_name')
    op.drop_index(op.f('ix_hentai_releases_series_name'), table_name='hentai_releases')
    op.drop_column('hentai_releases', 'series_name')
    # ### end Alembic commands ###
