"""Whoops, forgot ANOTHER column

Revision ID: af01f97c978e
Revises: 2939691825b4
Create Date: 2018-02-21 20:58:27.922767

"""

# revision identifiers, used by Alembic.
revision = 'af01f97c978e'
down_revision = '2939691825b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
import sqlalchemy_jsonfield

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hentai_releases', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('manga_releases', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga_releases', 'deleted')
    op.drop_column('hentai_releases', 'deleted')
    # ### end Alembic commands ###
