"""CIText origin/series names

Revision ID: b8e27eaa87b9
Revises: 0ab876947815
Create Date: 2018-09-11 04:02:50.189521

"""

# revision identifiers, used by Alembic.
revision = 'b8e27eaa87b9'
down_revision = '0ab876947815'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
import sqlalchemy_jsonfield

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hentai_releases', 'origin_name',
               existing_type=sa.TEXT(),
               type_=citext.CIText(),
               existing_nullable=True)
    op.alter_column('hentai_releases', 'series_name',
               existing_type=sa.TEXT(),
               type_=citext.CIText(),
               existing_nullable=True)
    op.alter_column('manga_releases', 'origin_name',
               existing_type=sa.TEXT(),
               type_=citext.CIText(),
               existing_nullable=True)
    op.alter_column('manga_releases', 'series_name',
               existing_type=sa.TEXT(),
               type_=citext.CIText(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manga_releases', 'series_name',
               existing_type=citext.CIText(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('manga_releases', 'origin_name',
               existing_type=citext.CIText(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hentai_releases', 'series_name',
               existing_type=citext.CIText(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hentai_releases', 'origin_name',
               existing_type=citext.CIText(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
